@startuml
!include ../../inc/settings.pu
left to right direction
title ロバストネス図 - 画面を切り替える

actor "ユーザ" as User
boundary "ヘッダー部" as HeaderPart
boundary "コントローラ画面" as ControllerPart
boundary "サーボ制御画面" as ServoControlPart
control "画面切替" as ChangePart

User --> HeaderPart : 画面を切り替える
HeaderPart --> ChangePart
ChangePart --> ControllerPart
ChangePart --> ServoControlPart

@enduml