@startuml
!include inc/settings.pu
title コンポーネント図 - システム全体

node "Main Board\n{hardware = Arduino Due}" as MainBoard {
  component "Communication" as Comm
  interface "Serial" as Serial
  Serial - Comm

  component "Servo Control" as ServoControl
  Comm ..> ServoControl

  component "Gyro Checker" as GyroChecker
  Comm ..> GyroChecker
  GyroChecker .> ServoControl
}

node "Communication Board\n{hardware = WROOM-ESP-32}" as CommBoard {
  component "WebSocket Server" as WebSocketServer
  interface "WebSocket" as WebSocket
  WebSocket - WebSocketServer

  component "Servo Control" as ServoControlE
  interface "Serial" as SerialC
  SerialC - ServoControlE

  WebSocketServer -[hidden]- ServoControlE
}

node "Controller\n{OS = Android}" as Controller {
  component "Controller App" as ControllerApp
  interface "Application GUI" as AppGui
  AppGui - ControllerApp
  note left of AppGui : for User
}

rectangle {
  node "Servo_1~10" as Servo_1
  node "Servo_11~18" as Servo_11
}

node "Battery\n{type = Le-Fe,\ncapacity = 6.6v}" as Battery

node "MicroSD" as MicroSD {
  database "Master\nData" as MasterData
}

node "Gyro Sensor" as GyroSensor

Controller -- CommBoard : tcp/ip
CommBoard - MainBoard : Serial
MainBoard --- MicroSD : SPI
MainBoard --- GyroSensor : I2C
MainBoard --- Servo_1 : Line x 10
CommBoard --- Servo_11 : Line x 8
MainBoard -- Battery : Line
CommBoard -- Battery : Line

ControllerApp ..> WebSocket : WebSocket
WebSocketServer ..> Serial : UART\n{baudrate=115200}
ServoControl ..> MasterData
ServoControl ..> SerialC : UART\n{baudrate=115200}
ServoControl ..> Servo_1
ServoControlE ..> Servo_11
GyroChecker ..> GyroSensor

@enduml
